# Generated by Django 2.2.14 on 2021-05-18 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=11, unique=True, verbose_name='account_number')),
                ('firstName', models.CharField(max_length=200, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=200, verbose_name='lastName')),
                ('town', models.CharField(max_length=50, verbose_name='town')),
                ('sex', models.CharField(max_length=1, verbose_name='sex')),
                ('born_year', models.DateField(default=datetime.date.today, verbose_name='born_year')),
            ],
        ),
    ]
